### PR TITLE
Adding spanish translation and updating build.gradle

### PR DESCRIPTION
**Pull request by LuisAlfredo92**
-Adding strings.xml for Spanish

**Optionally, you might reject this:**
-Update build.gradle (Done automatically by Android Studio)
-Marking "help_file_name" as untranslatable
-Some involuntary modifications on other files

### CODE REVIEW

**Comment by mirfatif** [comment]
Thanks for your interest. `strings.xml` doesn't contain all the translatable strings. It'd be better if you work on Crowdin: https://crowdin.com/project/pmx/es-ES

**Comment by mirfatif** [comment]
> Yesterday when I checked there wasn't any other languages apart of Russian

Correct. I add new language when someone is interested in translating.

> may you merge only the strings.xml for Spanish?

I've added you translation to Crowdin. You may please proceed there.

**Comment by LuisAlfredo92** [comment]
Okay, then I'll do it there, thanks a lot!

**Comment by mirfatif** [comment]
I have added the Spanish translation to new beta build. You can get the APK from Telegram group (https://t.me/PermissionManagerX) and test it. I have noted a few strings which need attention. In particular "[Backup / Restore](https://crowdin.com/translate/pmx/26/en-es?filter=basic&value=0#1346)" is too long. It doesn't fit in the left drawer. Paid features [description](https://crowdin.com/translate/pmx/26/en-es?filter=basic&value=0#4221) and [translation credits](https://crowdin.com/translate/pmx/26/en-es?filter=basic&value=0#5339) strings have bad formatting.

**Comment by LuisAlfredo92** [comment]
Okay, I will correct those and download the beta.
I thought they would be added until they get finished.

**Pull request closed without merging**
